/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * ANKAVEDA — Source Intelligence Engine
 * Lead Architect: Pawan Paji
 */

import { SourceCitation } from '../types';

export const SOURCE_TAXONOMY = {
  'Category A': {
    label: 'Category A — Classical / Primary Tradition',
    description: 'Directly sourced from classical Sanskrit, Prakrit, Tamil texts, historical astronomical treatises, and ancient manuscript traditions.',
    color: 'emerald',
    badge: 'Primary Manuscript / Classical Text'
  },
  'Category B': {
    label: 'Category B — Scholarly & Academic Research',
    description: 'Peer-reviewed research, critical editions, Oriental studies, and university publications (Oxford, Brill, Cambridge, Motilal Banarsidass).',
    color: 'sky',
    badge: 'Peer-Reviewed Academic'
  },
  'Category C': {
    label: 'Category C — Living Traditional Practice',
    description: 'Living regional Indian traditions, oral lineage teachings, and traditional Ank Jyotish practitioner lineages.',
    color: 'amber',
    badge: 'Living Traditional Lineage'
  },
  'Category D': {
    label: 'Category D — Modern Numerological Codification',
    description: '19th-21st century codifications including Chaldean, Pythagorean, Cheiro, Sepharial, Balliett, and Campbell systems.',
    color: 'purple',
    badge: 'Modern Codification (19th-21st c.)'
  },
  'Category E': {
    label: 'Category E — AI-Assisted Interpretation',
    description: 'Synthesized contextual analysis generated by Google Gemini using retrieved knowledge graph constraints and source boundaries.',
    color: 'rose',
    badge: 'AI-Assisted Interpretation'
  }
};

export const KNOWLEDGE_SOURCES: SourceCitation[] = [
  {
    id: 'src-brihat-samhita',
    title: 'Bṛhat Saṁhitā of Varāhamihira',
    tradition: 'Classical Indic Jyotiṣa & Astronomical Heritage',
    system: 'Indian Numerical & Planetary Associations',
    historicalPeriod: 'c. 6th Century CE (Gupta Era)',
    language: 'Sanskrit',
    originalScript: 'देवनागरी (Devanāgarī)',
    transliteration: 'Bṛhatsaṁhitā (Graha-Cāra Adhyāya)',
    translation: 'Extensive treatise on astral phenomena, numerical planetary attributes, gemstones, and directional energies.',
    sourceType: 'Primary',
    author: 'Varāhamihira',
    textOrManuscript: 'Critical Edition ed. M. Ramakrishna Bhat, Motilal Banarsidass',
    academicReference: 'Bhat, M. R. (1981). Varāhamihira’s Bṛhat Saṁhitā with English Translation. Motilal Banarsidass Publishers.',
    confidenceLevel: 'High',
    category: 'Category A',
    lastReviewedDate: '2026-08-15'
  },
  {
    id: 'src-katapayadi-aryabhata',
    title: 'Aryabhatiya & Sadratnamala (Katapayadi System)',
    tradition: 'Indian Mathematical & Linguistic Heritage',
    system: 'Ka-ṭa-pa-ya-ādi Numerical Mapping',
    historicalPeriod: 'c. 499 CE to 18th Century CE (Kerala School of Mathematics)',
    language: 'Sanskrit',
    originalScript: 'मलयाळम् / देवनागरी (Grantha / Devanāgarī)',
    transliteration: 'kādayaḥ prathamā varṇāḥ...',
    translation: 'Alphabetic-to-numeral encryption system where Sanskrit consonants represent digits 0 through 9.',
    sourceType: 'Primary',
    author: 'Aryabhata & Sankara Varman',
    textOrManuscript: 'Sadratnamala with commentary, Madras Government Oriental Series',
    academicReference: 'Sarma, K. V. (1973). A History of the Kerala School of Hindu Astronomy. Vishveshvaranand Vedic Research Institute.',
    confidenceLevel: 'High',
    category: 'Category A',
    lastReviewedDate: '2026-07-20'
  },
  {
    id: 'src-sankhya-karika',
    title: 'Sāṅkhyakārikā of Īśvarakṛṣṇa',
    tradition: 'Classical Sāṅkhya Philosophy',
    system: 'Enumerative Ontology (Tattva Saṅkhyā)',
    historicalPeriod: 'c. 4th Century CE',
    language: 'Sanskrit',
    originalScript: 'देवनागरी',
    transliteration: 'mūlaprakṛtiravikṛtir...',
    translation: 'Foundational text establishing reality through exact enumeration of the 25 cosmic principles (tattvas).',
    sourceType: 'Primary',
    author: 'Īśvarakṛṣṇa',
    textOrManuscript: 'Critically edited by S. S. Suryanarayana Sastri, University of Madras',
    academicReference: 'Larson, G. J. (2014). Classical Sāṃkhya: An Interpretation of its History and Meaning. Motilal Banarsidass.',
    confidenceLevel: 'High',
    category: 'Category A',
    lastReviewedDate: '2026-06-10'
  },
  {
    id: 'src-cheiro-book-of-numbers',
    title: 'Cheiro’s Book of Numbers',
    tradition: 'Chaldean-Hebrew Modern Synthesis',
    system: 'Chaldean Numerology & Compound Number Vibrations (10-52)',
    historicalPeriod: '1926 CE',
    language: 'English',
    sourceType: 'Modern',
    author: 'Count Louis Hamon (Cheiro)',
    textOrManuscript: 'Published by The London Publishing Co., 1926',
    academicReference: 'Hamon, L. (1926). Cheiro’s Book of Numbers. Herbert Jenkins Ltd., London.',
    confidenceLevel: 'High',
    category: 'Category D',
    lastReviewedDate: '2026-05-01'
  },
  {
    id: 'src-balliett-pythagorean',
    title: 'The Philosophy of Numbers: Their Tone & Colors',
    tradition: 'Modern Western Pythagorean Revival',
    system: 'Pythagorean Life Path, Expression & Soul Urge',
    historicalPeriod: '1908 CE',
    language: 'English',
    sourceType: 'Modern',
    author: 'L. Dow Balliett',
    textOrManuscript: 'L. Dow Balliett Publishing, Atlantic City, NJ',
    academicReference: 'Balliett, L. D. (1908). The Philosophy of Numbers: Their Tone and Colors. Atlantic City.',
    confidenceLevel: 'High',
    category: 'Category D',
    lastReviewedDate: '2026-04-18'
  },
  {
    id: 'src-ank-jyotish-living',
    title: 'Traditional Indian Aṅka Jyotiṣa (Vedic Numerology)',
    tradition: 'Living North and South Indian Astrological Lineages',
    system: 'Mūlāṅka (Root Number) & Bhāgyāṅka (Destiny Number)',
    historicalPeriod: 'Centuries-old living oral and manuscript practice',
    language: 'Hindi, Sanskrit, Gujarati, Tamil',
    sourceType: 'Traditional',
    author: 'Traditional Parāśara & Jaimini Lineage Commentators',
    textOrManuscript: 'Compilations across Brihat Parashara Hora Shastra oral glosses',
    academicReference: 'Raman, B. V. (1986). Notable Horoscopes and Astrological Magazine archives. Raman Publications, Bangalore.',
    confidenceLevel: 'Traditional Attribution',
    category: 'Category C',
    lastReviewedDate: '2026-08-01'
  },
  {
    id: 'src-oxford-indology-numbers',
    title: 'The Concept of Zero & Mathematical Philosophy in Early India',
    tradition: 'Academic Indological Scholarship',
    system: 'Historical Epistemology of Numbers',
    historicalPeriod: '2019 CE',
    language: 'English',
    sourceType: 'Academic',
    author: 'Oxford Indology & Science History Group',
    textOrManuscript: 'Oxford Studies in the History of Mathematics',
    academicReference: 'Plofker, K. (2009). Mathematics in India. Princeton University Press.',
    confidenceLevel: 'High',
    category: 'Category B',
    lastReviewedDate: '2026-03-12'
  }
];
